name: menu_chip
description: "A customizable chip widget with an integrated dropdown menu for single-value selection."
version: 2.0.0
repository: https://github.com/sainzriva/menu_chip.git
issue_tracker: https://github.com/sainzriva/menu_chip/issues

topics:
  - widget
  - material-design
  - chips
  - menu
  - dropdown

screenshots:
  - description: 'This screenshot shows the menu display.'
    path: screenshots/chip_menu.png

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
